test() ->
  try
    fail()
  catch<caret>